hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - batch_size=1
    - lr=5e-4,5e-5
  job:
    name: main_promptast_fsc_offline_hydra
    chdir: null
    override_dirname: batch_size=1,lr=5e-4,5e-5
    id: ???
    num: ???
    config_name: prompt_ast_fsc
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/ste/Internship/Code/SLURP_CL_example
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/ste/Internship/Code/SLURP_CL_example/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
data_path: /home/ste/Datasets
path_to_save_model: /models_PromptASTFSC/
download_dataset: false
seed: 0
device: cuda
batch_size: 1
num_workers: 10
lr: 5.0e-05
eval_every: 1
epochs: 100
label_smoothing: 0.0
weight_decay: 0.1
warmup_ratio: 2
n_mels: 768
n_seq_audio: 400
n_hidden_audio: 768,
n_head_audio: 8,
kernel_size: 3,
n_layer_audio: 18
drop: 0.1
n_vocab: 1000
n_hidden_text: 768
n_head_text: 8
n_layer_text: 6
n_feedforward: 3072
feed_forward_expansion_factor: 4
PAD_token: 0
memory_size: 0
fixed_memory: true
herding: random
herding_choices:
- random
- cluster
- barycenter
distillation-tau: 1.0
feat_space_kd: None
feat_space_choices:
- None
- only_rehe
- all
preds_space_kd: None
preds_space_kd_choices:
- None
- only_rehe
- all
increment: 3
initial_increment: 3
nb_tasks: 6
offline_train: true
total_classes: 18
nb_classes_noCL: 54
use_wandb: true
project_name: FSC Prompting on Audio Spectrogram Transformer
exp_name: FSC_AST_PROMPT_01
